### ISSUE TITLE
Telethon session to Pyrogram session

### ISSUE THREAD

**Issue by Thomas-op** [nazar220160/TGConvertor#1]
How to batch convert Telethon session files to Pyrogram session files?

**Comment by nazar220160** [comment]
from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio


async def main():
    session = await SessionManager.from_telethon_file(Path("telethon.session"))
    res = await session.to_pyrogram_file(Path("pyrogram.session"))
    print(res)


if __name__ == "__main__":
    asyncio.run(main())
