### ISSUE TITLE
Could not open key_data [ Called by ReadFile() ]

### ISSUE THREAD

**Issue by HaliliHorizon** [nazar220160/TGConvertor#2]

**Comment by nazar220160** [comment]
Maybe you have telegram open

**Comment by yarinhalili** [comment]
ive overcome this problem but got lots, how can i contact you

**Comment by yarinhalili** [comment]
I have 100 telethon Sessions+Jsons and their tdata and want to convert to pyrgogram sessions

**Comment by Deathcrash** [comment]
> У меня есть 100 сеансов телемарафона + Jsons и их tdata, и я хочу преобразовать их в сеансы пиргограммы.

mm
