### ISSUE TITLE
Problem after Converting TELETHON Sessions to PyroGram

### ISSUE THREAD

**Issue by devDarom** [nazar220160/TGConvertor#3]
**after i converting the sessions, i get an error which says that the pyrogram sessions are 'NoneType' object is not subscriptable**

from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio

API_ID = 4
API_HASH = "014b35b6184100b085b0d0572f9b5103"

# Define the main function
async def main():
    # Define the path to the Telethon session files folder and the Pyrogram session files folder
    telethon_folder = Path("telethon sessions")
    pyrogram_folder = Path("pyrogram sessions")
    # Iterate over all the files in the Telethon folder
    for telethon_session_file in telethon_folder.iterdir():
        # check if the file is a session file
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            # Create a session object from the Telethon session file
            session = await SessionManager.from_telethon_file(telethon_session_file)
            # Define the path for the Pyrogram session file
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            # Convert the session object to a Pyrogram session file
            res = await session.to_pyrogram_file(pyrogram_session_file)
            print(f'{telethon_session_file.name} converted successfully')
        else:
            # print a message if the file is not a session file
            print(f"{telethon_session_file} is not a session file")

async def write_file_names_to_txt(telethon_folder: Path):
    # Define the path for the txt file
    txt_file = Path("telethon_session_files.txt")
    # Open the txt file in write mode
    with open(txt_file, 'w') as f:
        # Iterate over all the files in the Telethon folder
        for telethon_session_file in telethon_folder.iterdir():
            # check if the file is a session file
            if telethon_session_file.suffix == ".session":
                # Write the file name to the txt file
                file_name = telethon_session_file.stem
                f.write("{\n")
                f.write('"phone":"'+file_name+'",\n'),
                f.write('"api_id": 4,\n'),
                f.write('"api_hash": "014b35b6184100b085b0d0572f9b5103"')
                f.write("},\n")

# Call the function in the main function
async def main():
    telethon_folder = Path("telethon sessions")
    pyrogram_folder = Path("pyrogram sessions")
    # call the function here
    await write_file_names_to_txt(telethon_folder)
    for telethon_session_file in telethon_folder.iterdir():
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            session = await SessionManager.from_telethon_file(telethon_session_file)
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            session = await session.to_pyrogram_file(pyrogram_session_file)
            if session is not None:
                print(f'{telethon_session_file.name} converted successfully')
                # use session object here
            else:
                print("Error: session object is None")
        else:
            print(f"{telethon_session_file} is not a session file")

            
# Check if the script is being run as the main program
if __name__ == "__main__":
    print("Start converting files")
    # Run the main function using the asyncio.run() method
    asyncio.run(main())
    print("All files have been converted successfully")

**Comment by NastinShalopai** [comment]
it may be too late to give an answer, but I found a solution in the library in the file pyro.py the to_file function does not record the version in the version table using the SQL environment.

I changed the to_file function TGConvertor\manager\sessions\pyro.py on:

    async def to_file(self, path: Path):
        async with aiosqlite.connect(path) as db:
            await db.executescript(SCHEMA)
            await db.commit()
            sql = "INSERT INTO sessions VALUES (?, ?, ?, ?, ?, ?, ?)"
            params = (
                self.dc_id,
                self.api_id,
                self.test_mode,
                self.auth_key,
                0,
                self.user_id or 9999,
                self.is_bot
            )
            await db.execute(sql, params)
            sql = "INSERT INTO version VALUES (?)"
            params = (
                3,
            )
            await db.execute(sql, params)
            await db.commit()

**Comment by Deathcrash** [comment]
``> it may be too late to give an answer, but I found a solution in the library in the file pyro.py the to_file function does not record the version in the version table using the SQL environment.
> 
> I changed the to_file function TGConvertor\manager\sessions\pyro.py on:
> 
> ```
> async def to_file(self, path: Path):
>     async with aiosqlite.connect(path) as db:
>         await db.executescript(SCHEMA)
>         await db.commit()
>         sql = "INSERT INTO sessions VALUES (?, ?, ?, ?, ?, ?, ?)"
>         params = (
>             self.dc_id,
>             self.api_id,
>             self.test_mode,
>             self.auth_key,
>             0,
>             self.user_id or 9999,
>             self.is_bot
>         )
>         await db.execute(sql, params)
>         sql = "INSERT INTO version VALUES (?)"
>         params = (
>             3,
>         )
>         await db.execute(sql, params)
>         await db.commit()
> ```


from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio

API_ID = 26755338
API_HASH = 'e75a6906b8b0416715b4325d75455b43'


async def main():
    # Define the path to the Telethon session files folder and the Pyrogram session files folder
    telethon_folder = Path("conv")
    pyrogram_folder = Path("pyro")
    # Iterate over all the files in the Telethon folder
    for telethon_session_file in telethon_folder.iterdir():
        # check if the file is a session file
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            # Create a session object from the Telethon session file
            session = await SessionManager.from_telethon_file(telethon_session_file)
            # Define the path for the Pyrogram session file
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            # Convert the session object to a Pyrogram session file
            res = await session.to_pyrogram_file(pyrogram_session_file)
            print(f'{telethon_session_file.name} converted successfully')
        else:
            # print a message if the file is not a session file
            print(f"{telethon_session_file} is not a session file")


async def write_file_names_to_txt(telethon_folder: Path):
    # Define the path for the txt file
    txt_file = Path("telethon_session_files.txt")
    # Open the txt file in write mode
    with open(txt_file, 'w') as f:
        # Iterate over all the files in the Telethon folder
        for telethon_session_file in telethon_folder.iterdir():
            # check if the file is a session file
            if telethon_session_file.suffix == ".session":
                # Write the file name to the txt file
                file_name = telethon_session_file.stem
                f.write("{\n")
                f.write('"phone":"' + file_name + '",\n'),
                f.write('"api_id": 26755338,\n'),
                f.write('"api_hash": "e75a6906b8b0416715b4325d75455b43"')
                f.write("},\n")

main()

**Comment by Deathcrash** [comment]
from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio

API_ID = 26755338
API_HASH = 'e75a6906b8b0416715b4325d75455b43'


async def main():
    # Define the path to the Telethon session files folder and the Pyrogram session files folder
    telethon_folder = Path("conv")
    pyrogram_folder = Path("pyro")
    # Iterate over all the files in the Telethon folder
    for telethon_session_file in telethon_folder.iterdir():
        # check if the file is a session file
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            # Create a session object from the Telethon session file
            session = await SessionManager.from_telethon_file(telethon_session_file)
            # Define the path for the Pyrogram session file
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            # Convert the session object to a Pyrogram session file
            res = await session.to_pyrogram_file(pyrogram_session_file)
            print(f'{telethon_session_file.name} converted successfully')
        else:
            # print a message if the file is not a session file
            print(f"{telethon_session_file} is not a session file")


async def write_file_names_to_txt(telethon_folder: Path):
    # Define the path for the txt file
    txt_file = Path("telethon_session_files.txt")
    # Open the txt file in write mode
    with open(txt_file, 'w') as f:
        # Iterate over all the files in the Telethon folder
        for telethon_session_file in telethon_folder.iterdir():
            # check if the file is a session file
            if telethon_session_file.suffix == ".session":
                # Write the file name to the txt file
                file_name = telethon_session_file.stem
                f.write("{\n")
                f.write('"phone":"' + file_name + '",\n'),
                f.write('"api_id": 26755338,\n'),
                f.write('"api_hash": "e75a6906b8b0416715b4325d75455b43"')
                f.write("},\n")

main()

**Comment by Deathcrash** [comment]
`from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio

API_ID = 26755338
API_HASH = 'e75a6906b8b0416715b4325d75455b43'


async def main():
    # Define the path to the Telethon session files folder and the Pyrogram session files folder
    telethon_folder = Path("conv")
    pyrogram_folder = Path("pyro")
    # Iterate over all the files in the Telethon folder
    for telethon_session_file in telethon_folder.iterdir():
        # check if the file is a session file
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            # Create a session object from the Telethon session file
            session = await SessionManager.from_telethon_file(telethon_session_file)
            # Define the path for the Pyrogram session file
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            # Convert the session object to a Pyrogram session file
            res = await session.to_pyrogram_file(pyrogram_session_file)
            print(f'{telethon_session_file.name} converted successfully')
        else:
            # print a message if the file is not a session file
            print(f"{telethon_session_file} is not a session file")


async def write_file_names_to_txt(telethon_folder: Path):
    # Define the path for the txt file
    txt_file = Path("telethon_session_files.txt")
    # Open the txt file in write mode
    with open(txt_file, 'w') as f:
        # Iterate over all the files in the Telethon folder
        for telethon_session_file in telethon_folder.iterdir():
            # check if the file is a session file
            if telethon_session_file.suffix == ".session":
                # Write the file name to the txt file
                file_name = telethon_session_file.stem
                f.write("{\n")
                f.write('"phone":"' + file_name + '",\n'),
                f.write('"api_id": 26755338,\n'),
                f.write('"api_hash": "e75a6906b8b0416715b4325d75455b43"')
                f.write("},\n")

main()`

**Comment by Deathcrash** [comment]
```
from TGConvertor.manager.manager import SessionManager
from pathlib import Path
import asyncio

API_ID = 26755338
API_HASH = 'e75a6906b8b0416715b4325d75455b43'


async def main():
    # Define the path to the Telethon session files folder and the Pyrogram session files folder
    telethon_folder = Path("conv")
    pyrogram_folder = Path("pyro")
    # Iterate over all the files in the Telethon folder
    for telethon_session_file in telethon_folder.iterdir():
        # check if the file is a session file
        if telethon_session_file.suffix == ".session":
            print(f'Converting {telethon_session_file.name}')
            # Create a session object from the Telethon session file
            session = await SessionManager.from_telethon_file(telethon_session_file)
            # Define the path for the Pyrogram session file
            pyrogram_session_file = pyrogram_folder / telethon_session_file.name
            # Convert the session object to a Pyrogram session file
            res = await session.to_pyrogram_file(pyrogram_session_file)
            print(f'{telethon_session_file.name} converted successfully')
        else:
            # print a message if the file is not a session file
            print(f"{telethon_session_file} is not a session file")


async def write_file_names_to_txt(telethon_folder: Path):
    # Define the path for the txt file
    txt_file = Path("telethon_session_files.txt")
    # Open the txt file in write mode
    with open(txt_file, 'w') as f:
        # Iterate over all the files in the Telethon folder
        for telethon_session_file in telethon_folder.iterdir():
            # check if the file is a session file
            if telethon_session_file.suffix == ".session":
                # Write the file name to the txt file
                file_name = telethon_session_file.stem
                f.write("{\n")
                f.write('"phone":"' + file_name + '",\n'),
                f.write('"api_id": 26755338,\n'),
                f.write('"api_hash": "e75a6906b8b0416715b4325d75455b43"')
                f.write("},\n")

main()
```

**Comment by Deathcrash** [comment]
RuntimeWarning: coroutine 'main' was never awaited
  main()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by Deathcrash** [comment]
thanks
