### ISSUE TITLE
How import telethon.session file and save to TData

### ISSUE THREAD

**Issue by DragoLifer** [nazar220160/TGConvertor#5]
Help me pls. I need function for import telethon.session file and then save this file to TData folder

**Comment by DragoLifer** [comment]
def main():
    session = SessionManager.from_telethon_file(Path("telethon.session"))
    res = session.to_tdata_folder('')
    print(res)
    
  I tried that, but it dont work

**Comment by nazar220160** [comment]
The library hasn't been updated for a long time, which may be why it doesn't work. Most likely this problem only occurs with telethon sessions

**Comment by DragoLifer** [comment]
can you give me some advice

**Comment by nazar220160** [comment]
You can find a fork to this repository that works with telethon sessions. Or become a sponsor of this project so that it continues to live

**Comment by nazar220160** [comment]
Fixed, update the library
