### ISSUE TITLE
telethon to pyrogram session dont work

### ISSUE THREAD

**Issue by porastomas** [nazar220160/TGConvertor#6]
hi
I tried like this, the session is created but is not recognized by pyrogram :(

from TGConvertor.manager.manager import SessionManager

API_ID = ''
API_HASH = ''

async def main():
session_manager = SessionManager(API_ID, API_HASH)
await session_manager.from_telethon_file("1.session")
await session_manager.to_pyrogram_file("01.session")

if name == "main":
import asyncio
asyncio.run(main())

**Comment by nazar220160** [comment]
Fixed, update the library
